### PR TITLE
prepare release v1.1.0

### PR DESCRIPTION
**Pull request by fredbi**
* describes changes and improvements in README (not change log yet)
* announces V2 in proposal doc

### CODE REVIEW

**Comment by Jacalz** [comment]
Thanks for working on this. The performance improvements will be great for Fyne. I'll try to have a look at integrating and testing the new version later in the week.

One problem that I see now is the Go 1.20 requirement. We are currently using 1.17 and planning on updating to 1.19 as the minimum for the next release a few months away.

**Comment by fredbi** [comment]
Thanks for the feedback @Jacalz 

* I've added go1.20 requirement to support errors.Join() and errors.Wrap() (an improvement to the stdlib that I've been expecting for a very long time). Perhaps I can rework this part and move it to v2 (after all, this is a kind of breaking change). I thought that now that go1.21 is out, most repos are moving up to at least go1.20... Please let me know.
* performances: I've worked on further optimizations and benchmark comparisons with net/url.URL: removing a few extraneous allocations (at the cost of code readability...) and preventing costly checks early should bring us to no more than 30% extra time when compared to the standard URL parser.
* still a few fixes needed regarding correctness of some edge cases. Worked quite a bit on making the tests more readable. Having to maintain this so many years after the first draft is indeed very instructive.

**Comment by fredbi** [comment]
@Jacalz  out of curiosity is "Fyne" somehow related to "Fyn"? How do you pronounce it?

**Comment by Jacalz** [comment]
> I thought that now that go1.21 is out, most repos are moving up to at least go1.20... Please let me know.

We are trying to stick with the version that the latest stable Debian Linux release has in its repos. It usually means that we are a little behind the current stable releases. This is to make sure that users on those systems doesn't have to immediately download some other Go version just to run their apps. It is also problematic if a Fyne application is accepted for inclusion in the repos and it can't be built with the available Go compiler version.

There are also cases where Go removes support for macOS and iOS versions which essentially makes old hardware e-waste. That's also a good reason for staying a few releases behind and giving the users some more time to upgrade.

It is indeed nice to use new features and I wish that the ecosystem could move a bit quicker sometimes but it is what it is.

**Comment by Jacalz** [comment]
> @Jacalz out of curiosity is "Fyne" somehow related to "Fyn"? How do you pronounce it

I don't think it is. Andrew was the one that created the project but I believe he said it was just a play on words.

Sorry but what is "Fyn"?

**Comment by andydotxyz** [comment]
There is a tenuous connection to geography as there is a large Loch in Scotland named Fyne, but it was more the name for names sake rather than any locality reason.

**Comment by fredbi** [comment]
> There is a tenuous connection to geography as there is a large Loch in Scotland named Fyne, but it was more the name for names sake rather than any locality reason.

Okay... I was thinking of the Danish island of Fyn (Funen), a haven of peace really...

**Comment by Jacalz** [comment]
As a Swede, I actually haven't been to Denmark all too much. I really should :)

**Comment by fredbi** [comment]
> > I thought that now that go1.21 is out, most repos are moving up to at least go1.20... Please let me know.
> 
> We are trying to stick with the version that the latest stable Debian Linux release has in its repos. It usually means that we are a little behind the current stable releases. This is to make sure that users on those systems doesn't have to immediately download some other Go version just to run their apps. It is also problematic if a Fyne application is accepted for inclusion in the repos and it can't be built with the available Go compiler version.
> 
> There are also cases where Go removes support for macOS and iOS versions which essentially makes old hardware e-waste. That's also a good reason for staying a few releases behind and giving the users some more time to upgrade.
> 
> It is indeed nice to use new features and I wish that the ecosystem could move a bit quicker sometimes but it is what it is.

ok @Jacalz got it. I am trying to emulate the errors.Join() that I want for go19. Something along the lines of github.com/fredbi/wrappable-errors but simpler. When successful I’ll revert the go.mos requirement to go1.19.

**Comment by Jacalz** [comment]
I tested the new release in Fyne and all tests passed (except for using a new Go version of course). Nice work. The improved performance and shorter startup time is a great :)

**Comment by fredbi** [comment]
> I tested the new release in Fyne and all tests passed (except for using a new Go version of course). Nice work. The improved performance and shorter startup time is a great :)

Thanks @Jacalz . I've brought back go1.19 compatibility (deferring go1.20 requirement to v2).
Cutting v1.1.0 now. Feel free to let me know about any issues.

**Comment by Jacalz** [comment]
Thanks. I'll try to get Fyne updated to Go 1.19 and to your new release. It will likely happen later in the week. I have a lot to do at the moment

**Pull request merged**
